// ============================================================================
// test_adc_distance_sw.cpp — Software ADC (Asymmetric Distance Computation)
// validation against golden fixtures generated by generate_fixtures.py --small
//
// Reads: codebook.bin, queries.bin, vectors.bin (PQ codes),
//        golden_distances.bin, golden_topk.bin, metadata.json
// All paths are relative to CORTEX_FIXTURE_DIR.
// ============================================================================

#include <gtest/gtest.h>
#include "fixture_loader.h"

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

// ============================================================================
// Anonymous namespace — internal helpers
// ============================================================================
namespace {

constexpr float kEpsilon = 5e-4f;

// --------------------------------------------------------------------------
// FixturePaths — simple path builder
// --------------------------------------------------------------------------
struct FixturePaths {
  std::string dir;

  explicit FixturePaths(const std::string& d) : dir(d) {}

  std::string metadata()        const { return dir + "metadata.json"; }
  std::string codebook()        const { return dir + "codebook.bin"; }
  std::string queries()         const { return dir + "queries.bin"; }
  std::string vectors()         const { return dir + "vectors.bin"; }
  std::string goldenDist()      const { return dir + "golden_distances.bin"; }
  std::string goldenTopK()      const { return dir + "golden_topk.bin"; }
};

// --------------------------------------------------------------------------
// TestConfig — parsed from metadata.json (no external JSON lib)
// --------------------------------------------------------------------------
struct TestConfig {
  int M = 0;
  int D = 0;
  int dsub = 0;
  int ksub = 0;
  int num_queries = 0;
  int num_vectors = 0;
  int top_k = 0;
};

// Minimal JSON int-key extractor — only handles the simple flat JSON we have.
static int jsonGetInt(const std::string& json, const std::string& key) {
  auto pos = json.find("\"" + key + "\"");
  if (pos == std::string::npos) return 0;
  pos = json.find(':', pos);
  if (pos == std::string::npos) return 0;
  // skip ':' and whitespace
  while (pos < json.size() && (json[pos] == ':' || json[pos] == ' ' || json[pos] == '\t'))
    ++pos;
  // parse leading digits
  int val = 0;
  bool neg = false;
  if (pos < json.size() && json[pos] == '-') { neg = true; ++pos; }
  while (pos < json.size() && json[pos] >= '0' && json[pos] <= '9') {
    val = val * 10 + (json[pos] - '0');
    ++pos;
  }
  return neg ? -val : val;
}

static void loadConfig(TestConfig& cfg, const FixturePaths& paths) {
  std::ifstream f(paths.metadata());
  if (!f.good()) { GTEST_SKIP() << "Cannot open " << paths.metadata(); return; }
  std::string json((std::istreambuf_iterator<char>(f)),
                    std::istreambuf_iterator<char>());

  cfg.M           = jsonGetInt(json, "M");
  cfg.D           = jsonGetInt(json, "D");
  cfg.dsub        = jsonGetInt(json, "dsub");
  cfg.ksub        = jsonGetInt(json, "ksub");
  cfg.num_queries = jsonGetInt(json, "num_queries");
  cfg.num_vectors = jsonGetInt(json, "num_vectors");
  cfg.top_k       = jsonGetInt(json, "top_k");
}

// --------------------------------------------------------------------------
// computeADC — pure-software ADC L2 distance
//
//   queries[qi][d]         : float,  dims = num_queries x D
//   codebook[m][k][j]      : float,  dims = M x ksub x dsub
//   codes[vi][m]           : uint8,  dims = num_vectors x M
//   distances[qi][vi]      : float, output, dims = num_queries x num_vectors
// --------------------------------------------------------------------------
static void computeADC(const float* queries, int num_queries,
                       const float* codebook, int M, int ksub, int dsub,
                       const uint8_t* codes, int num_vectors,
                       float* distances) {
  const int D = M * dsub;

  for (int qi = 0; qi < num_queries; ++qi) {
    // ---- step 1: build M x ksub distance table ----
    std::vector<float> table(static_cast<size_t>(M) * ksub);
    for (int m = 0; m < M; ++m) {
      const float* q_sub = queries + static_cast<size_t>(qi) * D + m * dsub;
      const float* cb_m  = codebook + static_cast<size_t>(m) * ksub * dsub;
      for (int k = 0; k < ksub; ++k) {
        float d2 = 0.0f;
        for (int j = 0; j < dsub; ++j) {
          float diff = q_sub[j] - cb_m[static_cast<size_t>(k) * dsub + j];
          d2 += diff * diff;
        }
        table[static_cast<size_t>(m) * ksub + k] = d2;
      }
    }

    // ---- step 2: accumulate for each encoded vector ----
    float* row = distances + static_cast<size_t>(qi) * num_vectors;
    for (int vi = 0; vi < num_vectors; ++vi) {
      float d2 = 0.0f;
      for (int m = 0; m < M; ++m) {
        d2 += table[static_cast<size_t>(m) * ksub + codes[static_cast<size_t>(vi) * M + m]];
      }
      row[vi] = d2;
    }
  }
}

// --------------------------------------------------------------------------
// reconstruct — build full D-dimensional vector from PQ codes
//   out[0..D-1] = codebook[0][codes[0]]  ++  codebook[1][codes[1]]  ++ ...
// --------------------------------------------------------------------------
static void reconstruct(const float* codebook, int M, int ksub, int dsub,
                        const uint8_t* codes, float* out) {
  for (int m = 0; m < M; ++m) {
    uint8_t c = codes[m];
    const float* centroid = codebook + (static_cast<size_t>(m) * ksub + c) * dsub;
    std::memcpy(out + static_cast<size_t>(m) * dsub, centroid,
                static_cast<size_t>(dsub) * sizeof(float));
  }
}

// --------------------------------------------------------------------------
// topKIndices — find indices of the K smallest distances (stable order)
//   Returns vector of (index, distance) sorted by distance ascending.
// --------------------------------------------------------------------------
struct IndexDist {
  int idx;
  float dist;
};

static std::vector<IndexDist> topKIndices(const float* distances, int n,
                                           int k) {
  std::vector<IndexDist> pairs;
  pairs.reserve(n);
  for (int i = 0; i < n; ++i) {
    pairs.push_back({i, distances[i]});
  }
  // stable sort matches numpy argsort(kind='mergesort') tie-breaking
  std::stable_sort(pairs.begin(), pairs.end(),
                   [](const IndexDist& a, const IndexDist& b) {
                     return a.dist < b.dist;
                   });
  if (k > n) k = n;
  pairs.resize(k);
  return pairs;
}

}  // anonymous namespace

// ============================================================================
// Tests
// ============================================================================

struct ADCDistanceTest : public ::testing::Test {
  FixturePaths paths;
  TestConfig cfg;
  std::vector<float> codebook;
  std::vector<float> queries;
  std::vector<uint8_t> codes;
  std::vector<float> golden_dist;
  std::vector<float> computed_dist;

  ADCDistanceTest()
      : paths(CORTEX_FIXTURE_DIR) { loadConfig(cfg, paths); }

  void SetUp() override {
    ASSERT_GT(cfg.M, 0);
    ASSERT_GT(cfg.D, 0);
    ASSERT_GT(cfg.dsub, 0);
    ASSERT_GT(cfg.ksub, 0);
    ASSERT_GT(cfg.num_queries, 0);
    ASSERT_GT(cfg.num_vectors, 0);

    // Load binary fixtures
    codebook = cortex::test::load_float_bin(paths.codebook());
    ASSERT_EQ(codebook.size(),
              static_cast<size_t>(cfg.M) * cfg.ksub * cfg.dsub);

    queries = cortex::test::load_float_bin(paths.queries());
    ASSERT_EQ(queries.size(),
              static_cast<size_t>(cfg.num_queries) * cfg.D);

    codes = cortex::test::load_uint8_bin(paths.vectors());
    ASSERT_EQ(codes.size(),
              static_cast<size_t>(cfg.num_vectors) * cfg.M);

    golden_dist = cortex::test::load_float_bin(paths.goldenDist());
    ASSERT_EQ(golden_dist.size(),
              static_cast<size_t>(cfg.num_queries) * cfg.num_vectors);

    // Precompute ADC distances (shared by all tests)
    computed_dist.resize(golden_dist.size());
    computeADC(queries.data(), cfg.num_queries,
               codebook.data(), cfg.M, cfg.ksub, cfg.dsub,
               codes.data(), cfg.num_vectors,
               computed_dist.data());
  }
};

// --------------------------------------------------------------------------
// Test 1 — GoldenMatches
//   Compare each computed ADC distance against golden_distances.bin.
// --------------------------------------------------------------------------
TEST_F(ADCDistanceTest, GoldenMatches) {
  for (int qi = 0; qi < cfg.num_queries; ++qi) {
    for (int vi = 0; vi < cfg.num_vectors; ++vi) {
      size_t idx = static_cast<size_t>(qi) * cfg.num_vectors + vi;
      EXPECT_NEAR(computed_dist[idx], golden_dist[idx], kEpsilon)
          << "  query=" << qi << "  vector=" << vi;
    }
  }
}

// --------------------------------------------------------------------------
// Test 2 — TopKMatches
//   Verify that the Top-K (smallest distances) match golden_topk.bin.
//   golden_topk layout: for each query, top_k entries of
//     uint64_t doc_addr + float distance  (little-endian)
// --------------------------------------------------------------------------
TEST_F(ADCDistanceTest, TopKMatches) {
  // Load golden topk
  std::ifstream f(paths.goldenTopK(), std::ios::binary);
  if (!f.good()) GTEST_SKIP() << "Cannot open " << paths.goldenTopK();

  for (int qi = 0; qi < cfg.num_queries; ++qi) {
    // Compute Top-K from our ADC distances
    const float* row = computed_dist.data() + static_cast<size_t>(qi) * cfg.num_vectors;
    auto topk = topKIndices(row, cfg.num_vectors, cfg.top_k);

    for (int ki = 0; ki < cfg.top_k; ++ki) {
      // Read golden entry
      uint64_t gold_idx;
      float gold_dist;
      f.read(reinterpret_cast<char*>(&gold_idx), sizeof(gold_idx));
      f.read(reinterpret_cast<char*>(&gold_dist), sizeof(gold_dist));

      EXPECT_EQ(static_cast<int>(gold_idx), topk[ki].idx)
          << "  query=" << qi << "  rank=" << ki
          << "  (computed idx=" << topk[ki].idx
          << "  dist=" << topk[ki].dist << ")";

      EXPECT_NEAR(topk[ki].dist, gold_dist, kEpsilon)
          << "  query=" << qi << "  rank=" << ki
          << "  gold_idx=" << gold_idx;
    }
  }
}

// --------------------------------------------------------------------------
// Test 3 — SelfDistance
//   Reconstruct the first database vector from its PQ codes (using the
//   codebook centroids) and verify that its ADC self-distance ≈ 0.
// --------------------------------------------------------------------------
TEST_F(ADCDistanceTest, SelfDistance) {
  // Reconstruct vector-0 from PQ codes
  std::vector<float> reconstructed(cfg.D);
  reconstruct(codebook.data(), cfg.M, cfg.ksub, cfg.dsub,
              codes.data(), reconstructed.data());

  // Compute ADC distance of reconstructed vector against its own PQ codes
  //   i.e. treat [reconstructed] as the only query
  std::vector<float> self_dist(1 * cfg.num_vectors);
  computeADC(reconstructed.data(), 1,
             codebook.data(), cfg.M, cfg.ksub, cfg.dsub,
             codes.data(), cfg.num_vectors,
             self_dist.data());

  // The distance of the first vector to its own encoding must be ~0
  EXPECT_NEAR(self_dist[0], 0.0f, kEpsilon)
      << "  Self-distance of first PQ-encoded vector (reconstructed vs "
         "codes[0]) is not near zero";
}
